# Generated by Django 3.2 on 2022-11-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221105_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_home',
            name='book',
        ),
    ]
