# Generated by Django 3.2 on 2022-11-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='添付ファイル'),
        ),
    ]
